export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const EVENT_NAME_STATE_CHANGE = 'EVENT_NAME_STATE_CHANGE'
export const EVENT_DESCRIPTION_STATE_CHANGE = 'EVENT_DESCRIPTION_STATE_CHANGE'